/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cadastro.equipamentos;

public class App {

    public static void main(String[] args) {
        // equipamentos novos
        Equipamento e1 = new Equipamento("1", "E1");
        Equipamento e2 = new Equipamento("2", "E2");
        Equipamento e3 = new Equipamento("3", "E3");
        Equipamento e4 = new Equipamento("4", "E4");


        CadastroEquipamento ce = new CadastroEquipamento();

        // salvando
        ce.salvar(e1);
        ce.salvar(e2);
        ce.salvar(e3);
        ce.salvar(e4);

        // pesquisando pelo codigo
        System.out.println(ce.pesquisar("2").getNome());
        System.out.println(ce.pesquisar("4").getNome());
    }
}